name             = "aicg"
main             = "src/index.js"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "SESSIONS"
id      = "7efe2f42d42b44b58473e7e02a04a00f"

[vars]
GITHUB_OWNER    = "codywoods8899"
GITHUB_REPO     = "mevrelbank"
SESSION_TTL_MS  = "86400000"
